[project]
name = "ambarawa-retrieval-prod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "baml-py>=0.214.0",
    "dotenv>=0.9.9",
    "logfire>=4.16.0",
    "numpy>=2.3.5",
    "pillow>=12.0.0",
    "pydantic>=2.12.5",
    "pydantic-ai-slim[openai]>=1.35.0",
]

[tool.pyrefly]
python-version = "3.13"
python-interpreter-path = ".venv/Scripts/python"

project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

project-excludes = ["**/node_modules", "**/__pycache__", "**/*venv/**", "**/.[!/.]*/**"]

[tool]
