# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def GetBookConditionData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BookConditionData:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookConditionData", llm_response=llm_response, mode="request")
        return typing.cast(types.BookConditionData, __result__)

    def GetBookContentHints(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BookContentHints:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookContentHints", llm_response=llm_response, mode="request")
        return typing.cast(types.BookContentHints, __result__)

    def GetBookMainData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BookMainData:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookMainData", llm_response=llm_response, mode="request")
        return typing.cast(types.BookMainData, __result__)

    def GetBookPublisherData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BookPubAndDistDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookPublisherData", llm_response=llm_response, mode="request")
        return typing.cast(types.BookPubAndDistDetails, __result__)

    def GetBookrawVisual(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RawAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookrawVisual", llm_response=llm_response, mode="request")
        return typing.cast(types.RawAnalysis, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def GetBookConditionData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BookConditionData:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookConditionData", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BookConditionData, __result__)

    def GetBookContentHints(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BookContentHints:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookContentHints", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BookContentHints, __result__)

    def GetBookMainData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BookMainData:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookMainData", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BookMainData, __result__)

    def GetBookPublisherData(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BookPubAndDistDetails:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookPublisherData", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BookPubAndDistDetails, __result__)

    def GetBookrawVisual(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RawAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GetBookrawVisual", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RawAnalysis, __result__)

    