# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (22)
# #########################################################################

class BookAuthor(BaseModel):
    author_in_origin_script: typing.Optional[str] = None
    author_in_latin_script: typing.Optional[str] = None

class BookConditionData(BaseModel):
    physicalObservations: typing.List["PhysicalObservation"]
    conditionAnalysis: typing.Optional["ConditionAnalysis"] = None
    printTypeAnalysis: typing.Optional["PrintTypeAnalysis"] = None
    Condition: typing.Optional[types.BookConditionEnum] = None
    PrintType: typing.Optional[types.BookPrintTypeEnum] = None

class BookContentHints(BaseModel):
    extractedTextSnippets: typing.List[str]
    nerCandidates: typing.List[str]
    contentClues: typing.List[str]
    bookBlurbText: typing.Optional[str] = None
    bookNERData: typing.List[str]
    fictionAnalysis: typing.Optional[str] = None
    isFiction: typing.Optional[bool] = None
    genreAnalysis: typing.Optional[str] = None
    bookGenre: typing.List[str]
    bookContextHints: typing.Optional[str] = None

class BookMainData(BaseModel):
    extractionEvidence: typing.List["TextExtractionEvidence"]
    languageScriptAnalysis: typing.Optional[str] = None
    dataComparisons: typing.List["DataComparison"]
    transliterationReasoning: typing.Optional[str] = None
    title: typing.Optional["BookTitle"] = None
    language: typing.List[str]
    script: typing.List[str]
    authors: typing.List["BookAuthor"]
    translator: typing.Optional[typing.List["BookTranslator"]] = None
    isbn_13: typing.Optional[str] = None
    isbn_10: typing.Optional[str] = None
    published_year: typing.Optional[int] = None
    confidence: typing.Optional[float] = None

class BookPubAndDistDetails(BaseModel):
    extractionEvidence: typing.List["PublisherTextEvidence"]
    roleDistinction: typing.Optional["RoleDistinction"] = None
    dataComparisons: typing.List["PublisherDataComparison"]
    transliterationStrategy: typing.Optional[str] = None
    geographicAnalysis: typing.Optional[str] = None
    publisher_name: typing.Optional["PublisherName"] = None
    publisher_location: typing.Optional["PublisherLocation"] = None
    editor: typing.Optional["Editor"] = None
    distributor_name: typing.Optional["DistributorName"] = None
    distributor_location: typing.Optional["DistributorLocation"] = None
    confidence: typing.Optional[float] = None
    image_count: typing.Optional[int] = None

class BookTitle(BaseModel):
    title_in_origin_script: typing.Optional[str] = None
    title_in_latin_script: typing.Optional[str] = None
    title_in_indonesian: typing.Optional[str] = None

class BookTranslator(BaseModel):
    translators_in_origin_script: typing.Optional[str] = None
    translators_in_latin_script: typing.Optional[str] = None

class ConditionAnalysis(BaseModel):
    overallAssessment: typing.Optional[str] = None
    conditionReasoning: typing.Optional[str] = None
    preservationUrgency: typing.Optional[str] = None

class DataComparison(BaseModel):
    fieldName: typing.Optional[str] = None
    fromImages: typing.Optional[str] = None
    fromNotes: typing.Optional[str] = None
    agreement: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None
    finalDecision: typing.Optional[str] = None

class DistributorLocation(BaseModel):
    original_script: typing.Optional[str] = None
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None
    country: typing.Optional[str] = None

class DistributorName(BaseModel):
    original_script: typing.Optional[str] = None
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None

class Editor(BaseModel):
    original_script: typing.Optional[str] = None
    romanized: typing.Optional[str] = None

class PhysicalObservation(BaseModel):
    imageNumber: typing.Optional[int] = None
    bookComponent: typing.Optional[str] = None
    observedFeatures: typing.List[str]
    severityLevel: typing.Optional[str] = None
    readabilityImpact: typing.Optional[str] = None

class PrintTypeAnalysis(BaseModel):
    coverMaterial: typing.Optional[str] = None
    bindingType: typing.Optional[str] = None
    printQualityIndicators: typing.List[str]
    printTypeReasoning: typing.Optional[str] = None

class PublisherDataComparison(BaseModel):
    fieldName: typing.Optional[str] = None
    fromImages: typing.Optional[str] = None
    fromNotes: typing.Optional[str] = None
    agreement: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None
    finalDecision: typing.Optional[str] = None

class PublisherLocation(BaseModel):
    original_script: typing.Optional[str] = None
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None
    country: typing.Optional[str] = None

class PublisherName(BaseModel):
    original_script: typing.Optional[str] = None
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None

class PublisherTextEvidence(BaseModel):
    imageNumber: typing.Optional[int] = None
    pageType: typing.Optional[str] = None
    location: typing.Optional[str] = None
    extractedText: typing.Optional[str] = None
    textType: typing.Optional[str] = None
    scriptIdentified: typing.Optional[str] = None
    confidencePublisher: typing.Optional[str] = None

class RawAnalysis(BaseModel):
    coverPageDescription: typing.Optional[str] = None
    backCoverDescription: typing.Optional[str] = None
    colophonPageDescription: typing.Optional[str] = None
    otherPageDescriptions: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class RoleDistinction(BaseModel):
    publisherIdentified: typing.Optional[bool] = None
    editorIdentified: typing.Optional[bool] = None
    distributorIdentified: typing.Optional[bool] = None
    printerIdentified: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None

class TextExtractionEvidence(BaseModel):
    imageNumber: typing.Optional[int] = None
    location: typing.Optional[str] = None
    extractedText: typing.Optional[str] = None
    textType: typing.Optional[str] = None
    scriptIdentified: typing.Optional[str] = None
    confidence: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
