# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BookAuthor": types.BookAuthor,
    "stream_types.BookAuthor": stream_types.BookAuthor,

    "types.BookConditionData": types.BookConditionData,
    "stream_types.BookConditionData": stream_types.BookConditionData,

    "types.BookContentHints": types.BookContentHints,
    "stream_types.BookContentHints": stream_types.BookContentHints,

    "types.BookMainData": types.BookMainData,
    "stream_types.BookMainData": stream_types.BookMainData,

    "types.BookPubAndDistDetails": types.BookPubAndDistDetails,
    "stream_types.BookPubAndDistDetails": stream_types.BookPubAndDistDetails,

    "types.BookTitle": types.BookTitle,
    "stream_types.BookTitle": stream_types.BookTitle,

    "types.BookTranslator": types.BookTranslator,
    "stream_types.BookTranslator": stream_types.BookTranslator,

    "types.ConditionAnalysis": types.ConditionAnalysis,
    "stream_types.ConditionAnalysis": stream_types.ConditionAnalysis,

    "types.DataComparison": types.DataComparison,
    "stream_types.DataComparison": stream_types.DataComparison,

    "types.DistributorLocation": types.DistributorLocation,
    "stream_types.DistributorLocation": stream_types.DistributorLocation,

    "types.DistributorName": types.DistributorName,
    "stream_types.DistributorName": stream_types.DistributorName,

    "types.Editor": types.Editor,
    "stream_types.Editor": stream_types.Editor,

    "types.PhysicalObservation": types.PhysicalObservation,
    "stream_types.PhysicalObservation": stream_types.PhysicalObservation,

    "types.PrintTypeAnalysis": types.PrintTypeAnalysis,
    "stream_types.PrintTypeAnalysis": stream_types.PrintTypeAnalysis,

    "types.PublisherDataComparison": types.PublisherDataComparison,
    "stream_types.PublisherDataComparison": stream_types.PublisherDataComparison,

    "types.PublisherLocation": types.PublisherLocation,
    "stream_types.PublisherLocation": stream_types.PublisherLocation,

    "types.PublisherName": types.PublisherName,
    "stream_types.PublisherName": stream_types.PublisherName,

    "types.PublisherTextEvidence": types.PublisherTextEvidence,
    "stream_types.PublisherTextEvidence": stream_types.PublisherTextEvidence,

    "types.RawAnalysis": types.RawAnalysis,
    "stream_types.RawAnalysis": stream_types.RawAnalysis,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.RoleDistinction": types.RoleDistinction,
    "stream_types.RoleDistinction": stream_types.RoleDistinction,

    "types.TextExtractionEvidence": types.TextExtractionEvidence,
    "stream_types.TextExtractionEvidence": stream_types.TextExtractionEvidence,


    "types.BookConditionEnum": types.BookConditionEnum,

    "types.BookPrintTypeEnum": types.BookPrintTypeEnum,

}