# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class BookConditionEnum(str, Enum):
    BARU = "BARU"
    SANGAT_BAIK = "SANGAT_BAIK"
    BAIK = "BAIK"
    CUKUP_BAIK = "CUKUP_BAIK"
    DITERIMA = "DITERIMA"
    BURUK = "BURUK"

class BookPrintTypeEnum(str, Enum):
    HARDCOVER = "HARDCOVER"
    PAPERBACK = "PAPERBACK"
    FOTOKOPI = "FOTOKOPI"

# #########################################################################
# Generated classes (22)
# #########################################################################

class BookAuthor(BaseModel):
    author_in_origin_script: str
    author_in_latin_script: str

class BookConditionData(BaseModel):
    physicalObservations: typing.List["PhysicalObservation"]
    conditionAnalysis: "ConditionAnalysis"
    printTypeAnalysis: "PrintTypeAnalysis"
    Condition: BookConditionEnum
    PrintType: BookPrintTypeEnum

class BookContentHints(BaseModel):
    extractedTextSnippets: typing.List[str]
    nerCandidates: typing.List[str]
    contentClues: typing.List[str]
    bookBlurbText: typing.Optional[str] = None
    bookNERData: typing.List[str]
    fictionAnalysis: str
    isFiction: bool
    genreAnalysis: str
    bookGenre: typing.List[str]
    bookContextHints: typing.Optional[str] = None

class BookMainData(BaseModel):
    extractionEvidence: typing.List["TextExtractionEvidence"]
    languageScriptAnalysis: str
    dataComparisons: typing.List["DataComparison"]
    transliterationReasoning: str
    title: "BookTitle"
    language: typing.List[str]
    script: typing.List[str]
    authors: typing.List["BookAuthor"]
    translator: typing.Optional[typing.List["BookTranslator"]] = None
    isbn_13: typing.Optional[str] = None
    isbn_10: typing.Optional[str] = None
    published_year: typing.Optional[int] = None
    confidence: float

class BookPubAndDistDetails(BaseModel):
    extractionEvidence: typing.List["PublisherTextEvidence"]
    roleDistinction: "RoleDistinction"
    dataComparisons: typing.List["PublisherDataComparison"]
    transliterationStrategy: str
    geographicAnalysis: str
    publisher_name: "PublisherName"
    publisher_location: "PublisherLocation"
    editor: typing.Optional["Editor"] = None
    distributor_name: typing.Optional["DistributorName"] = None
    distributor_location: typing.Optional["DistributorLocation"] = None
    confidence: float
    image_count: int

class BookTitle(BaseModel):
    title_in_origin_script: str
    title_in_latin_script: str
    title_in_indonesian: str

class BookTranslator(BaseModel):
    translators_in_origin_script: str
    translators_in_latin_script: str

class ConditionAnalysis(BaseModel):
    overallAssessment: str
    conditionReasoning: str
    preservationUrgency: str

class DataComparison(BaseModel):
    fieldName: str
    fromImages: str
    fromNotes: str
    agreement: bool
    reasoning: str
    finalDecision: str

class DistributorLocation(BaseModel):
    original_script: str
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None
    country: str

class DistributorName(BaseModel):
    original_script: str
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None

class Editor(BaseModel):
    original_script: str
    romanized: typing.Optional[str] = None

class PhysicalObservation(BaseModel):
    imageNumber: int
    bookComponent: str
    observedFeatures: typing.List[str]
    severityLevel: str
    readabilityImpact: str

class PrintTypeAnalysis(BaseModel):
    coverMaterial: str
    bindingType: str
    printQualityIndicators: typing.List[str]
    printTypeReasoning: str

class PublisherDataComparison(BaseModel):
    fieldName: str
    fromImages: str
    fromNotes: str
    agreement: bool
    reasoning: str
    finalDecision: str

class PublisherLocation(BaseModel):
    original_script: str
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None
    country: str

class PublisherName(BaseModel):
    original_script: str
    romanized: typing.Optional[str] = None
    english_translation: typing.Optional[str] = None
    indonesian_translation: typing.Optional[str] = None

class PublisherTextEvidence(BaseModel):
    imageNumber: int
    pageType: str
    location: str
    extractedText: str
    textType: str
    scriptIdentified: str
    confidencePublisher: str

class RawAnalysis(BaseModel):
    coverPageDescription: str
    backCoverDescription: str
    colophonPageDescription: str
    otherPageDescriptions: typing.Optional[str] = None

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class RoleDistinction(BaseModel):
    publisherIdentified: bool
    editorIdentified: bool
    distributorIdentified: bool
    printerIdentified: bool
    reasoning: str

class TextExtractionEvidence(BaseModel):
    imageNumber: int
    location: str
    extractedText: str
    textType: str
    scriptIdentified: str
    confidence: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
